13 sprint/ 1 review
Klementor/java-shareit pull request #1
Opened 2023-02-01 16:33 UTC by Klementor

2023-02-01 17:18 UTC, Frilock requested changes
Добрый день, в целом все хорошо, критики не вижу. Пара мелких комментариев на Ваше усмотрение, в целом можно принимать.

2023-02-01 17:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/handler/GlobalErrorHandler.java
> +    public ErrorResponse notFoundExceptionHandler(NotFoundException ex) {
Принято исключение "e" называть =)

2023-02-01 17:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            boolean nameContains = item.getName().toLowerCase().contains(text);
Можно заменить на StringUtils.containsIgnoreCase =)

2023-02-01 17:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (text == null || text.isEmpty()) {
StringUtils.isBlank

2023-02-01 17:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +        UserResponseDto userResponseDto = new UserResponseDto();
Предложил бы Dtoшки через билдер сделать, но в целом на ваше усмотрение. Просто это более распространённый подход

2023-02-01 17:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        id++;
Можно с предыдущей строчкой обьединить

2023-02-01 21:35 UTC, Klementor commented on src/main/java/ru/practicum/shareit/exception/handler/GlobalErrorHandler.java
> +    public ErrorResponse notFoundExceptionHandler(NotFoundException ex) {
А ex, чтобы при поиске не было кучи переменных которые тоже на e начинаются) Читал, что так называют

2023-02-01 22:01 UTC, Klementor commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        id++;
Да, можно, но мне почему-то показалось, что так лучше код читается. Визуально как-то сразу понятно становится что происходит. Поэтому решил так оставить

2023-02-02 05:52 UTC, Frilock approved these changes
Принял

2023-03-03 12:12 UTC, merged